### PR TITLE
Added italian translation

### PR DESCRIPTION
**Pull request by nico202**
I didn't know if I had to copy other xlm too

### CODE REVIEW

**Comment by phikal** [comment]
To tell you the truth, I don't know either. Can you post a screenshot of how the game look like in italian?

**Comment by nico202** [comment]
Here the screenshots! :)
screenshot_2015-08-22-14-58-48
screenshot_2015-08-22-14-47-13
screenshot_2015-08-22-14-47-07
screenshot_2015-08-22-14-47-03
screenshot_2015-08-22-14-47-00

**Comment by phikal** [comment]
Great, lots of thanks! Can you just tell me how to write "translated to Italian by @nico202 " in Italian for the next release?

**Comment by nico202** [comment]
"tradotto in italiano da @nico202"

**Pull request merged**
